config/routes.rb
Rails.application.routes.draw do

 resources :clinicas
 root 'clinicas#index'
 post "/" => "clinicas#index"
 get  '/pruebas',    to: 'static_pages#pruebas'
 get  '/informacion',   to: 'static_pages#informacion'
 resources :users

 get  '/centros',   to: 'clinicas#index'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinic.rb
class Clinic < ApplicationRecord    
        
end

app/models/geojson_builder.rb
class GeojsonBuilder
  def build_event(event, geojson)
    geojson << {
      type: "Feature",
      geometry: {
        type: "Point",
        coordinates: [clinics.lon, clinics.lat] # this part is tricky
      },
      properties: {
        title: event.title,
        address: event.address,
        :"marker-color" => "#FFFFFF",
        :"marker-symbol" => "circle",
        :"marker-size" => "medium",
      }
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clinicas_controller.rb
class ClinicasController < ApplicationController

  def show
    @clinic = Clinic.find(params[:id])
  end

  def index
    @clinics =  Clinic.all
    if params[:clinic_type].present?
      @clinics =  @clinics.where(:tipo2 => params[:clinic_type].keys)
    end
    if params[:cost].present?
      @clinics =  @clinics.where(:costoi => params[:cost].keys)
    end
    if params[:time].present?
      @clinics =  @clinics.where(:tiempoi => params[:time].keys)
    end
    if params[:help].present?
      @clinics =  @clinics.where(:consejeriai => params[:help].keys)
    end
    if params[:direction].present?
      @clinics =  @clinics.where(:delegacion => params[:direction].keys)
    end

	  @clinics = @clinics.paginate(page: params[:page], :per_page => 8).order('prioridad DESC')
    @clinic_type = params[:clinic_type].as_json()
    @cost = params[:cost].as_json()
    @time = params[:time].as_json()
    @help = params[:help].as_json()
    @direction = params[:direction].as_json()
    return @clinics, @clinic_type,@cost,@time,@help,@direction
  end

end

app/controllers/encuesta_controller.rb
class EncuestaController < ApplicationController

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def pruebas
  end

  def informacion
  end
    
  def encuesta
      render layout: "encuesta"
  end
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

 def index
    @users = User.paginate(page: params[:page], :per_page => 9)     
 end    
    
  
end

app/controllers/users_controller_REMOTE_25798.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

 def index
    @users = User.paginate(page: params[:page], :per_page => 6)
  end    
    
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
      base_title = "Sin Dudas"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
    
end

app/helpers/clinicas_helper.rb
module ClinicasHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clinicas/_clinicsshow.html.erb
<div id="products" class="row list-group" >
    <% if @clinics.blank? %>
  <h4>No hay clinicas con esas caracteristicas.</h4>
    <% else %>
    <% @clinics.each_with_index do |clinic, index| %>
        <div class="item  col-lg-3">
            <div class="thumbnail">
                <div class="caption">
                    <div class="link-to-map">
                        <a href="#ex1-<%= index %>" rel="modal:open" id="to-modal-<%= index %>">
                            <span class="glyphicon glyphicon-arrow-right"></span>
                        </a>
                    </div>
                    <h4 class="group inner list-group-item-heading"><%= clinic.institucion %></h4>
                    <p class="adress"><%= clinic.direccion %></p>
                    <div class="row" style=" display: flex;height: 100%;">
                    <div class="col-xs-6 telefono" style=" display: inline-block;align-self: flex-end;" href="tel:+155<%= clinic.telefono %>"><%= clinic.telefono  %></div>
                    <div class="col-xs-6 horario" style=" display: inline-block;align-self: flex-end;">
                    <% unless clinic.horariolv == '' && clinic.horarios == ''  && clinic.horariod == ''%>
                        <strong>L-V </strong> <%= clinic.horariolv=='' ? 'Cerrado' : clinic.horariolv %><br>
                        <strong>S </strong> <%= clinic.horarios=='' ? 'Cerrado' : clinic.horarios %><br>
                        <strong>D </strong> <%= clinic.horariod=='' ? 'Cerrado' : clinic.horariod %><br>
                    <% end %>
                    <% unless clinic.horarionotas == '' %>
                    <%= clinic.horarionotas %><br>
                    <% end %>

                    </div>
                    </div>
                    <hr>

                    <div class="row servicios">
                         <div class="col-xs-6 specs-1">
                             <span class="<%= 'servicios-no' if clinic.tipoi == 'Rápida'  %>" style="color:#DDDDDD;font-size:12px;" >&#11044;&nbsp;&nbsp;<span style="color:#4A4A4A;;font-size:13px;">Prueba Rápida</span></span><br>
                         <span class="<%= 'servicios-si' if clinic.costoi != 'Gratuita' %>" style="color:#7ED321;font-size:12px;" >&#11044;&nbsp;&nbsp;<span style="color:#4A4A4A;;font-size:13px;">Gratuita</span></span><br>
                          <span class="<%= 'servicios-si' if clinic.tipoinstitucion != 'Pública' %>" style="color:#7ED321;font-size:12px;">&#11044;&nbsp;&nbsp;<span style="color:#4A4A4A;;font-size:13px;">Servicio Público</span></span>

                         </div>
                         <div class="col-xs-6 specs-1">
                     <span class="<%= 'servicios-no' if clinic.pits != '' %>" style="color:#7ED321;font-size:12px;">&#11044;&nbsp;&nbsp;<span style="color:#4A4A4A;;font-size:13px;"> Prueba de ITS</span></span><br>
                     <span class="<%= 'servicios-no' if clinic.consejeriai != 'No' %>" style="color:#DDDDDD;font-size:12px;" >&#11044;&nbsp;&nbsp;<span style="color:#4A4A4A;;font-size:13px;">Consejería</span></span>


                         </div>


                    </div>

              </div>
            </div>
        </div>

        <div id="ex1-<%= index %>" class="map-modal" style="display:none;fluid: true">
                        <div class="row">
                            <div class="col-sm-7">
                                <div id="mapid-<%= index %>" class="mapas-modal">
                                </div>
                            </div>

                            <div class="col-sm-5 modal-content-columns">
                                 <h4 class="name-clinic-modal"><%= clinic.institucioncorta %></h4>
                                 <div class="row">
                                 <div class="col-sm-6">
                                   <p class="modal-interior-title">Teléfono<br>
                                     <a class="modal-interior-content"><%= clinic.telefono %><br>
                                         <a class="modal-interior-content"><%= clinic.notastelefono %><br>
                                         </a></p>
                                     <p class="modal-interior-title">Dirección<br>
                                         <a class="modal-interior-content" href="http://maps.google.com/?q=<%= clinic.direccion %>"><%= clinic.direccion %>
                                     </a></p>
                                     <p class="modal-interior-title">Horarios<br>

                                  <a class="modal-interior-content">Lunes:   <%= clinic.horariolv=='' ? 'Cerrado' : clinic.horariolv %></a><br>
                                     <a class="modal-interior-content">Martes:    <%= clinic.horariolv=='' ? 'Cerrado' : clinic.horariolv %></a><br>
                                     <a class="modal-interior-content">Miercoles:    <%= clinic.horariolv=='' ? 'Cerrado' : clinic.horariolv %></a><br>
                                         <a class="modal-interior-content">Jueves:    <%= clinic.horariolv=='' ? 'Cerrado' : clinic.horariolv %></a><br>
                                         <a class="modal-interior-content">Viernes:    <%= clinic.horariolv=='' ? 'Cerrado' : clinic.horariolv %></a><br>
                                         <a class="modal-interior-content">Sabado:    <%= clinic.horarios=='' ? 'Cerrado' : clinic.horarios %></a><br>
                                         <a class="modal-interior-content">Domingo:    <%= clinic.horariod=='' ? 'Cerrado' : clinic.horariod %></a><br><br>
                                         <a class="modal-interior-content">    <%= clinic.horarionotas %></a>

                                           </p>
									  
                                    

                                 </div>
                                 <div class="col-sm-6 modal-interno-derecha">
                                     <p class="modal-interior-title">Servicio<br>
                                     <a class="modal-interior-content"><%= clinic.tipoinstitucion %>
                                     </a></p>
                                      <p class="modal-interior-title">Costo<br>
                                      <a class="modal-interior-content"><%= clinic.costo %><br>
                                          <a class="modal-interior-content"><%= clinic.notascosto %>
                                      </a></p>
                                         <p class="modal-interior-title">Prueba VIH<br>
                                             <a class="modal-interior-content"><%= clinic.tipoi %>
                                     </a></p>
                                         <p class="modal-interior-title">Consejeria<br>
                                             <a class="modal-interior-content"><%= clinic.consejeria %>
                                     </a></p>
                                           <p class="modal-interior-title">Antes necesitas<br>
                                             <a class="modal-interior-content"><%= clinic.preparacion %>
                                     </a></p>
                                        <p class="modal-interior-title">Otras pruebas de infecciones de transmisión sexual disponibles<br>
                                             <a class="modal-interior-content"><%= clinic.pits %>
                                     </a></p>
									 <p class="modal-interior-title">Tiempo para resultados<br>
                                         <a class="modal-interior-content" ><%= clinic.tiemporesultados %>
                                     </a></p>


                                 </div>
                                 </div>
                            </div>

                        </div>

        </div>
        <script>
            if (<%=index%> == 0) {
              var all_maps = [];
            }
            all_maps.push(L.map('mapid-<%= index %>').setView([<%= clinic.lat %>, <%= clinic.lon %>], 13));
            var mymap = all_maps[<%= index %>];
                    L.tileLayer('https://api.mapbox.com/styles/v1/eclarkgd/ciwfc2mce004b2plkmujdb3no/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZWNsYXJrZ2QiLCJhIjoiY2lraXVvaWlzMDUzN3RubTZ2OHBscWRxciJ9.ikI5wjFM2RNcoOrssqx2Zg', {
                    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
                    maxZoom: 18, maxZoom: 18, }).addTo(mymap);
                    var marker = L.marker([<%= clinic.lat %>, <%= clinic.lon %>]).addTo(mymap);
                    $('#ex1-<%=index%>').on($.modal.OPEN, function () {
                         all_maps[<%=index%>].invalidateSize();
                    });
        </script>




        <% end %>
    </div>
    <% end %>

app/views/clinicas/index.html.erb
<% provide(:title, "") %>

 <%= render 'layouts/jumbotron' %>

    <div class="jumbotron" id="content">   

       <%= render 'layouts/fullcliniclist' %> 
         
    </div>

app/views/clinicas/new.html.erb
<h1>Clinicas#new</h1>
<%= @clinic.institucion %>

app/views/clinicas/show.html.erb
<%= @clinic.institucion %>

app/views/layouts/_clinicfilter.html.erb
<form action="/" method="post">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

    <div class="btn-group btn-group-justified my-btn-group-responsive" id="selector">
      <div class="btn-group" id="button-start" >
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" style="line-height:110%;">
            Tipo de prueba </button>
        <ul class="dropdown-menu" role="menu">
          <% if ! @clinic_type.blank? %>
            <% Clinic.select('tipo2').all().distinct.each do |f| %>
            <li><%= check_box_tag "clinic_type[#{f.tipo2}]", "#{f.tipo2}", @clinic_type.key?("#{f.tipo2}")%>
            <label><%= f.tipo2 %></label> </li>
            <% end %>
          <%else%>
            <% Clinic.select('tipo2').all().distinct.each do |f| %>
            <li><%= check_box_tag "clinic_type[#{f.tipo2}]", "#{f.tipo2}"%>
            <label><%= f.tipo2 %></label> </li>
            <%end%>
          <%end%>
        </ul>
    </div>

  <div class="btn-group">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" style="line-height:110%;">
          Costo </button>
    <ul class="dropdown-menu" role="menu">
        <% if ! @cost.blank? %>
          <% Clinic.select('costoi').all().distinct.each do |f| %>
          <li><%= check_box_tag "cost[#{f.costoi}]", "#{f.costoi}", @cost.key?("#{f.costoi}")%>
          <label><%= f.costoi %></label> </li>
          <% end %>
        <%else%>
          <% Clinic.select('costoi').all().distinct.each do |f| %>
          <li><%= check_box_tag "cost[#{f.costoi}]", "#{f.costoi}"%>
          <label><%= f.costoi %></label> </li>
          <%end%>
        <%end%>
      </ul>
   </div>

  <div class="btn-group">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" style="line-height:110%;">
          Tiempo para resultados </button>
    <ul class="dropdown-menu" role="menu">
        <% if ! @time.blank? %>
          <% Clinic.select('tiempoi').all().distinct.each do |f| %>
          <li><%= check_box_tag "time[#{f.tiempoi}]", "#{f.tiempoi}", @time.key?("#{f.tiempoi}")%>
          <label><%= f.tiempoi %></label> </li>
          <% end %>
        <%else%>
          <% Clinic.select('tiempoi').all().distinct.each do |f| %>
          <li><%= check_box_tag "time[#{f.tiempoi}]", "#{f.tiempoi}"%>
          <label><%= f.tiempoi %></label> </li>
          <%end%>
        <%end%>
      </ul>
   </div>

  <div class="btn-group">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" style="line-height:110%;">
          Asesoría </button>
    <ul class="dropdown-menu" role="menu">
        <% if ! @help.blank? %>
          <% Clinic.select('consejeriai').all().distinct.each do |f| %>
          <li><%= check_box_tag "help[#{f.consejeriai}]", "#{f.consejeriai}", @help.key?("#{f.consejeriai}")%>
          <label><%= f.consejeriai %></label> </li>
          <% end %>
        <%else%>
          <% Clinic.select('consejeriai').all().distinct.each do |f| %>
          <li><%= check_box_tag "help[#{f.consejeriai}]", "#{f.consejeriai}"%>
          <label><%= f.consejeriai %></label> </li>
          <%end%>
        <%end%>
      </ul>
   </div>
  <div class="btn-group" id="button-endnext">
    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" style="line-height:110%;">
          Delegación </button>
    <ul class="dropdown-menu" role="menu">
        <% if ! @direction.blank? %>
          <% Clinic.select('delegacion').all().distinct.each do |f| %>
          <li><%= check_box_tag "delegacion[#{f.delegacion}]", "#{f.delegacion}", @direction.key?("#{f.delegacion}")%>
          <label><%= f.delegacion %></label> </li>
          <% end %>
        <%else%>
          <% Clinic.select('delegacion').all().distinct.each do |f| %>
          <li><%= check_box_tag "direction[#{f.delegacion}]", "#{f.delegacion}"%>
          <label><%= f.delegacion %></label> </li>
          <%end%>
        <%end%>
      </ul>
   </div>


    <div class="btn-group" id="button-end">
            <div class="btn btn-primary btn btn-default btn-lg">
                <%= submit_tag "Busca una prueba",name: "Search"   %>
            </div>
  </div>

</form>
</div>

app/views/layouts/_clinicgrid.html.erb
<div class="container">
    <br><br><br>
    <%= render(
    partial: 'clinicas/clinicsshow',
    locals: {clinicas: @clinics }
    ) %>
    <% if ! @clinics.blank? %>
    <form action="/" method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <div id="infinite-scrolling">
            <%= will_paginate @clinics,:params => { :clinic_type => @clinic_type,
                      :cost=>@cost, :time=>@time,:help=>@help,:direction=>@direction},
                  :previous_label => '<', :next_label => '>', :inner_window => 1, :outer_window => 0  %>
        </div>
    </form>

    <% end %>

</div>

app/views/layouts/_footer.html.erb
    <footer class="footer">
        <div class="container">
            <div class="row"> 
                
            <div class="col-sm-2" >
            
                <%= link_to image_tag("03-Fundamenta.svg", alt: "sd", style:"height:150px" ), root_path, id: "logo-fundamenta" %>          
               
            </div>
                
             <div class="col-sm-2" >
             <%= link_to image_tag("01–MXDigital.svg",alt: "sd", style:"height:150px" ), "http://www.gob.mx/mexicodigital" , id: "logo-mxdigital", target: "_blank" %><br>          
             
            
            </div>
                
            <div class="col-sm-2" >
                        

            
            
            </div>
                
                
                 <div class="col-sm-2" >
            
				

            
            </div>
                
            
                
                
            
                
            <div class="col-sm-2 footer-text">
            <br><br>
                      
            </div>
                
            <div class="col-sm-2 footer-text">
            <br><br>
            <a><b>Contacto</b></a>
            <br> <br>
            <a>Te escuchamos en <a href="mailto:contacto@sindudas.mx" target="_top" id="contacto-mail">contacto@sindudas.mx</a></a> 
            <br> <br>
            <a><b>Acerca</b></a>
            <br><br>
            <a href="/informacion" target="_top" id="acerca-footer">¿Qué es sindudas.mx?</a>   
            </div>              
                
            </div>  
            <br>
        </div>
        <div class="subfooter">
            <div class="container">
                <a style="line-height: 350%;"> <%= link_to image_tag("sd_beta_blanco.svg", alt: "sd", style:"height:50px;color:white;" ), root_path, id: "logo-footer" %></a>
            </div>
            
        </div>


    </footer>
  

   

app/views/layouts/_fullcliniclist.html.erb
<div id="seccion-lista" class="container" >
    
    <%= render 'layouts/clinicfilter' %>
          

    <div id="clinicas">   
        <%= render 'layouts/clinicgrid' %>

    </div>
          
</div>

app/views/layouts/_head.html.erb
<title><%= full_title(yield(:title)) %></title>
  <%= favicon_link_tag 'Favicon-02.ico' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  <%= csrf_meta_tags %>
  <!-- BOOTSTRAP -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src='https://api.mapbox.com/mapbox-gl-js/v0.36.0/mapbox-gl.js'></script>
  <link href='https://api.mapbox.com/mapbox-gl-js/v0.36.0/mapbox-gl.css' rel='stylesheet'>

<script>
$(function(){
    $("#text"+(new Date().getTime() % 2)).css("display", "block");
});
</script>

<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-98397620-1', 'auto');
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->

app/views/layouts/_jumbotron.html.erb
   <div class="jumbotron" id="intro">      
       <div class="container" id="content">
                      <br><br><br>
        <div class="row">
            <div class="col-sm-9" ><p id="text0"><a style="color:#C4B60E"><strong>Quítate la duda y hazte la prueba.</strong></a><br>
                Recuerda que una prueba de VIH sólo es efectiva si se realiza entre las seis y doce semanas posteriores a un posible contacto de riesgo. Encuentra aquí tus opciones.</p></div>
            
        </div>
           <br><br><br>
       </div>                 
    </div>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="container">   
      
      <%= link_to image_tag("sd_beta.svg", alt: "sd", style:"height:50px;color:#000000" ), root_path, id: "logo-nav" %>
    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "¿Qué es sindudas?",   informacion_path,  'data-no-turbolink' => true %></li>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="background-color:#f8e71c;">
    
  <head>
      <%= render 'layouts/head' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>  
    <%= render 'layouts/footer' %>  
  </body>
    
</html>

app/views/layouts/encuesta.html.erb
<!DOCTYPE html>
<html style="background-color:#f8e71c;">
    
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">  
    <%= render 'layouts/head' %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>  
  </body>
    
</html>

app/views/static_pages/encuesta.html.erb
<% provide(:title, "esentrehombres") %>

<div class="container" id="logo-encuesta" style="font-family: 'Roboto Condensed', sans-serif !important;"><br><br><br><%= link_to image_tag("logoencuestalargo.svg", alt: "sd", style:"height:35%;width:35%;color:#4a4a4a" ), root_path, id: "github" %>
    
    
<script type="text/javascript" >document.write('<script src="http' + ( ("https:" == document.location.protocol) ? "s" : "") + '://www.surveygizmo.com/s3/2969704/d7142d735127?__output=embedjs&__ref=' + escape(document.location.origin + document.location.pathname) + '" type="text/javascript" ></scr'  + 'ipt>');</script>
</div>

app/views/static_pages/informacion.html.erb
<% provide(:title, "Información") %>

<container>	
<h1>¿Qué es sindudas?</h1>
<h3>
SinDudas.mx es una herramienta para localizar sitios que ofrezcan pruebas de detección de infecciones y enfermedades de transmisión sexual. En la versión beta_ podrás encontrar laboratorios y organizaciones que presten sus servicios en la Ciudad de México y el área metropolitana.
</h3>

<h3>
El sitio brinda información sobre el proceso, disponibilidad y calidad de los servicios con fichas únicas para cada laboratorio o institución, además de horarios de servicios e información de contacto.</h3>

<h3>
En la siguiente fase del sitio podrás encontrar un componente de contenidos para aprender sobre las posibilidades de riesgo de contagio de enfermedades e infecciones de transmisión sexual y las acciones para reducirlas. La plataforma en esta primera versión agrupa recursos públicos y privados disponibles para la detección del VIH e información específica sobre las pruebas disponibles para la CDMX.

</h3>


<h3>
Esta iniciativa es sin fines de lucro y busca generar un espacio seguro y con información de calidad enfocada a hombres que tienen sexo con otros hombres.</h2>


<h3>
Nos gustaría agregar más ciudades pronto y para eso necesitamos ayuda. Si eres diseñador, programador, analista, activista, médico o sólo interesado y quieres colaborar o tienes ideas sobre cómo mejorar el sitio escríbenos a contacto@sindudas.mx.</h3>
</container>

app/views/static_pages/pruebas.html.erb
<% provide(:title, "Pruebas") %>
<h1>pruebas</h1>

app/views/users/index.html.erb
<% provide(:title, "") %>

 <%= render 'layouts/jumbotron' %>

    <div class="jumbotron" id="content">   

       <%= render 'layouts/fullcliniclist' %> 
         
    </div>

  
 

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.nameshort %>